# Generated by Django 4.0.3 on 2022-03-14 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=100)),
                ('stu_class', models.IntegerField(max_length=2)),
                ('stu_phone', models.CharField(max_length=20)),
                ('stu_roll', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentAdmin',
            fields=[
                ('studentdetails_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='api.studentdetails')),
            ],
            bases=('api.studentdetails',),
        ),
    ]
